Repository piuswalter/Chess-AI, pull requests merged in 2022-03, with the labels that each got.

#46 Reverted evaluation order change
  src/Exercise02AI.ipynb
  src/Exercise04AI.ipynb
Labels: enhancement

#47 Change evaluation time and best move calculation
  src/Exercise02AI.ipynb
  src/Exercise04AI.ipynb
Labels: enhancement

#48 Changed statistics run to use python files
  .github/workflows/statistics.yml
  .github/workflows/testing.yml
  .gitignore
  scripts/games_count.sh
  scripts/nbconverter_template/conf.json
  scripts/nbconverter_template/index.py.j2
  scripts/print_status.sh
  scripts/server_setup.sh
  scripts/setup.sh
  scripts/stats.sh
  src/Exercise02AI.ipynb
  src/Exercise03AI.ipynb
  src/Exercise04AI.ipynb
  src/Exercise05AI.ipynb
  src/Exercise06AI.ipynb
  src/Exercise07AI.ipynb
  src/Main.ipynb
  src/Statistics.ipynb
  src/StockfishPlayer.ipynb
  src/chess_custom.ipynb
Labels: enhancement

#50 Alpha beta pruning
  .github/workflows/statistics.yml
  .github/workflows/testing.yml
  .gitignore
  scripts/config.json
  scripts/csv_export/export.py
  scripts/csv_export/pgn.py
  scripts/games_count.sh
  scripts/nb_exec.sh
  scripts/nbconverter_template/conf.json
  scripts/nbconverter_template/index.py.j2
  scripts/print_status.sh
  scripts/server_setup.sh
  scripts/setup.sh
  scripts/stats.sh
  src/AIBaseClass.ipynb
  src/Exercise01AI.ipynb
  src/Exercise02AI.ipynb
  src/Exercise03AI.ipynb
  src/Exercise04AI.ipynb
  src/Exercise05AI.ipynb
  src/Exercise06AI.ipynb
  src/Exercise07AI.ipynb
  src/Exercise07LiteAI.ipynb
  src/HumanPlayer.ipynb
  src/Main.ipynb
  src/Statistics.ipynb
  src/StockfishPlayer.ipynb
  src/chess_custom.ipynb
  statistics/statistics.xlsx
  statistics/statistics_2022-03-09_Ex01-07AI.xlsx
  statistics/statistics_gamefiles.zip
Labels: documentation, enhancement

#51 Add Exercise 05-07
  .github/workflows/statistics.yml
  .github/workflows/testing.yml
  .gitignore
  scripts/config.json
  scripts/csv_export/export.py
  scripts/csv_export/pgn.py
  scripts/games_count.sh
  scripts/nb_exec.sh
  scripts/nbconverter_template/conf.json
  scripts/nbconverter_template/index.py.j2
  scripts/print_status.sh
  scripts/server_setup.sh
  scripts/setup.sh
  scripts/stats.sh
  src/AIBaseClass.ipynb
  src/Exercise01AI.ipynb
  src/Exercise02AI.ipynb
  src/Exercise03AI.ipynb
  src/Exercise04AI.ipynb
  src/Exercise05AI.ipynb
  src/Exercise06AI.ipynb
  src/Exercise07AI.ipynb
  src/Exercise07LiteAI.ipynb
  src/HumanPlayer.ipynb
  src/Main.ipynb
  src/Statistics.ipynb
  src/StockfishPlayer.ipynb
  src/chess_custom.ipynb
  statistics/statistics.xlsx
  statistics/statistics_2022-03-09_Ex01-07AI.xlsx
  statistics/statistics_gamefiles.zip
Labels: enhancement

#52 Added unit tests and small fixes
  src/Exercise01AI.ipynb
  src/Exercise02AI.ipynb
  src/Exercise03AI.ipynb
  src/Exercise04AI.ipynb
  src/Exercise05AI.ipynb
  src/Exercise06AI.ipynb
  src/Exercise07AI.ipynb
  src/Exercise07LiteAI.ipynb
  src/HumanPlayer.ipynb
  src/Main.ipynb
  src/StockfishPlayer.ipynb
  src/chess_custom.ipynb
Labels: bug, enhancement

#54 Updated descriptions
  src/Exercise02AI.ipynb
  src/Exercise03AI.ipynb
  src/Exercise05AI.ipynb
  src/Exercise06AI.ipynb
  src/Exercise07AI.ipynb
Labels: documentation

#56 Refactor minimax implementations
  src/Exercise02AI.ipynb
  src/Exercise04AI.ipynb
  src/Exercise05AI.ipynb
  src/Exercise06AI.ipynb
  src/Exercise07AI.ipynb
  src/Exercise07LiteAI.ipynb
Labels: enhancement

#57 Added time and evaluation statistics
  src/Exercise02AI.ipynb
  src/Exercise07AI.ipynb
  src/HumanPlayer.ipynb
  src/Main.ipynb
  src/Statistics.ipynb
Labels: enhancement
