Repository piuswalter/Chess-AI, pull requests merged in 2022-05, with the labels that each got.

#59 Exercise08ai
  .github/workflows/statistics.yml
  .github/workflows/testing.yml
  README.md
  scripts/config.json
  scripts/csv_export/export.py
  scripts/csv_export/pgn.py
  src/AIBaseClass.ipynb
  src/Display-saved-game.ipynb
  src/Exercise01AI.ipynb
  src/Exercise02AI.ipynb
  src/Exercise03AI.ipynb
  src/Exercise04AI.ipynb
  src/Exercise05AI.ipynb
  src/Exercise06AI.ipynb
  src/Exercise07AI.ipynb
  src/Exercise07LiteAI.ipynb
  src/Exercise08AI.ipynb
  src/HumanPlayer.ipynb
  src/Main.ipynb
  src/Statistics.ipynb
  src/StockfishPlayer.ipynb
  src/chess_custom.ipynb
  statistics/statistics_2022-03-09_Ex01-07AI.xlsx
Labels: documentation, enhancement

#60 Update config to list type
  .github/workflows/statistics.yml
  .github/workflows/testing.yml
  .gitignore
  scripts/config.json
  src/Statistics.ipynb
  src/StockfishPlayer.ipynb
Labels: enhancement

#61 Statistics
  src/Statistics_Discussion.ipynb
  src/images/AI04Results.png
  src/images/AI06Results.png
  src/images/AI08Results.png
  src/images/CacheHitsBlack.png
  src/images/CacheHitsWhite.png
  src/images/Depth3AvgDuration.png
  src/images/Depth3MaxDepthAvgDuration.png
  src/images/Depth4AvgDuration.png
  src/images/Depth4MaxDepthAvgDuration.png
  src/images/RAM_Ex08AI_vs_Stockfish.png
  src/images/ResultsBlackDepth3.png
  src/images/ResultsBlackDepth4.png
  src/images/ResultsWhiteDepth3.png
  src/images/ResultsWhiteDepth4.png
Labels: documentation

#62 Development
  .github/workflows/statistics.yml
  .github/workflows/testing.yml
  .gitignore
  README.md
  scripts/config.json
  scripts/csv_export/export.py
  scripts/csv_export/pgn.py
  scripts/nbconverter_template/index.py.j2
  src/AIBaseClass.ipynb
  src/Display-saved-game.ipynb
  src/Exercise01AI.ipynb
  src/Exercise02AI.ipynb
  src/Exercise03AI.ipynb
  src/Exercise04AI.ipynb
  src/Exercise05AI.ipynb
  src/Exercise06AI.ipynb
  src/Exercise07AI.ipynb
  src/Exercise07LiteAI.ipynb
  src/Exercise08AI.ipynb
  src/HumanPlayer.ipynb
  src/Main.ipynb
  src/Statistics.ipynb
  src/Statistics_Discussion.ipynb
  src/StockfishPlayer.ipynb
  src/chess_custom.ipynb
  src/images/AI04Results.png
  src/images/AI06Results.png
  src/images/AI08Results.png
  src/images/CacheHitsBlack.png
  src/images/CacheHitsWhite.png
  src/images/Depth3AvgDuration.png
  src/images/Depth3MaxDepthAvgDuration.png
  src/images/Depth4AvgDuration.png
  src/images/Depth4MaxDepthAvgDuration.png
  src/images/RAM_Ex08AI_vs_Stockfish.png
  src/images/ResultsBlackDepth3.png
  src/images/ResultsBlackDepth4.png
  src/images/ResultsWhiteDepth3.png
  src/images/ResultsWhiteDepth4.png
  src/requirements.txt
  statistics/statistics_2022-03-09_Ex01-07AI.xlsx
Labels: documentation, enhancement

#63 Fixed piece square tables
  src/Exercise03AI.ipynb
  src/Exercise08AI.ipynb
Labels: bug

#64 Added nodes count stats
  src/Exercise02AI.ipynb
  src/Exercise03AI.ipynb
  src/Exercise04AI.ipynb
  src/Exercise05AI.ipynb
  src/Exercise06AI.ipynb
  src/Exercise07AI.ipynb
  src/Exercise08AI.ipynb
  src/Main.ipynb
Labels: enhancement

#65 Beschreibung der Memoisierung aktualisiert
  src/Exercise04AI.ipynb
  src/Exercise06AI.ipynb
  src/Literaturverzeichnis.ipynb
Labels: documentation

#66 Fixed Exercise08AI
  scripts/csv_export/export.py
  src/Exercise08AI.ipynb
  src/Statistics.ipynb
Labels: bug
