Repository piuswalter/Chess-AI, pull requests merged in 2022-06, with the labels that each got.

#67 Piuswalter/small fixes
  src/AIBaseClass.ipynb
  src/Exercise02AI.ipynb
  src/Exercise03AI.ipynb
  src/Exercise05AI.ipynb
  src/Exercise07AI.ipynb
  src/Literaturverzeichnis.ipynb
  src/Statistics_Discussion.ipynb
Labels: documentation

#68 Added more information to the PST tables
  src/Exercise03AI.ipynb
Labels: documentation

#70 Added description for save game function
  src/Main.ipynb
Labels: documentation

#71 Integrated material values into PST
  src/Exercise03AI.ipynb
Labels: enhancement

#69 Added description for minimax algorithm
  src/Exercise02AI.ipynb
  src/Literaturverzeichnis.ipynb
  src/images/400px-Minimax.svg.png
Labels: documentation

#72 Updated Ex05AI Description
  src/Exercise05AI.ipynb
  src/Exercise07AI.ipynb
  src/Literaturverzeichnis.ipynb
  src/images/AlphaBetaPruning.jpg
Labels: documentation

#74 Optimized push and pop at evaluation
  src/Exercise02AI.ipynb
  src/Exercise03AI.ipynb
  src/Exercise05AI.ipynb
  src/Exercise07AI.ipynb
  src/Exercise08AI.ipynb
  src/HumanPlayer.ipynb
  src/Main.ipynb
Labels: documentation, enhancement

#73 Updated Ex07AI description
  src/Exercise05AI.ipynb
  src/Exercise07AI.ipynb
  src/Literaturverzeichnis.ipynb
Labels: documentation

#75 Added export of average node count to statistics
  scripts/csv_export/export.py
  src/Statistics.ipynb
Labels: enhancement

#76 Add unittest descriptions
  src/Exercise01AI.ipynb
  src/Exercise02AI.ipynb
  src/Exercise03AI.ipynb
  src/Exercise04AI.ipynb
  src/Exercise05AI.ipynb
  src/Exercise06AI.ipynb
  src/Exercise07AI.ipynb
  src/Exercise08AI.ipynb
Labels: documentation

#79 Piuswalter/formatting
  src/AIBaseClass.ipynb
  src/Display-saved-game.ipynb
  src/Exercise01AI.ipynb
  src/Exercise02AI.ipynb
  src/Exercise03AI.ipynb
  src/Exercise04AI.ipynb
  src/Exercise05AI.ipynb
  src/Exercise06AI.ipynb
  src/Exercise07AI.ipynb
  src/Exercise08AI.ipynb
  src/HumanPlayer.ipynb
  src/Literaturverzeichnis.ipynb
  src/Main.ipynb
  src/Statistics-Discussion.ipynb
  src/Statistics.ipynb
  src/StockfishPlayer.ipynb
  src/requirements.txt
Labels: documentation

#80 Antonplagemann/spelling
  src/AIBaseClass.ipynb
  src/Exercise03AI.ipynb
  src/Exercise04AI.ipynb
  src/Exercise05AI.ipynb
  src/Exercise06AI.ipynb
  src/Exercise08AI.ipynb
  src/Main.ipynb
  src/Statistics-Discussion.ipynb
  src/Statistics.ipynb
  src/StockfishPlayer.ipynb
Labels: documentation

#81 Enhance statistics discussions
  src/Statistics-Discussion.ipynb
  src/images/AI04Results.png
  src/images/AI06Results.png
  src/images/AI08Results.png
  src/images/Depth3AvgDuration.png
  src/images/Depth3AvgNodes.png
  src/images/Depth3MaxDepthAvgDuration.png
  src/images/Depth4AvgDuration.png
  src/images/Depth4AvgNodes.png
  src/images/Depth4MaxDepthAvgDuration.png
  src/images/Ex08ResultsDepth4MaxDepth8.png
  src/images/StockfishResultsDepth4.png
Labels: enhancement

#82 Add conclusion and fix tpyos
  src/Statistics-Discussion.ipynb
Labels: documentation

#83 Experiments
  scripts/config.json
  src/ExperimentalAI.ipynb
  src/Main.ipynb
  src/Statistics.ipynb
  src/images/ExperimentalAI_cache_hits.png
  src/images/ExperimentalAI_cache_size.png
  src/images/ExperimentalAI_duration.png
  src/images/ExperimentalAI_nodes.png
  src/images/Stockfish_vs_ExperimentalAI.png
Labels: enhancement

#85 Fix import
  src/Statistics.ipynb
Labels: bug
