Repository piuswalter/Chess-AI, pull requests merged in 2022-01, with the labels that each got.

#32 Minor fixes
  .github/workflows/statistics.yml
  .gitignore
  src/AIBaseClass.ipynb
  src/Exercise02AI.ipynb
  src/Exercise04AI.ipynb
  src/Main.ipynb
  src/Statistics.ipynb
Labels: bug, documentation, enhancement

#33 improve documentation of Exercise04AI
  src/Exercise04AI.ipynb
Labels: documentation

#36 Added description to Exercise03AI
  src/Exercise03AI.ipynb
Labels: documentation

#34 Described statistics notebook
  src/Statistics.ipynb
Labels: documentation

#37 Philipp/scripts
  .github/workflows/statistics.yml
  .github/workflows/testing.yml
  README.md
  scripts/setup.sh
  scripts/stats.sh
Labels: enhancement

#35 Updated Minimax and Memoization
  .github/workflows/statistics.yml
  src/AIBaseClass.ipynb
  src/Exercise02AI.ipynb
  src/Exercise04AI.ipynb
Labels: bug, enhancement

#38 Remove minimax outcome evaluation
  .github/workflows/statistics.yml
  src/Exercise02AI.ipynb
  src/Exercise04AI.ipynb
  src/Main.ipynb
  src/Statistics.ipynb
Labels: enhancement

#40 Optimizations
  .github/workflows/statistics.yml
  .github/workflows/testing.yml
  scripts/stats.sh
  src/AIBaseClass.ipynb
  src/Display-saved-game.ipynb
  src/Exercise01AI.ipynb
  src/Exercise02AI.ipynb
  src/Exercise03AI.ipynb
  src/Exercise04AI.ipynb
  src/HumanPlayer.ipynb
  src/Main.ipynb
  src/Statistics.ipynb
  src/StockfishPlayer.ipynb
Labels: bug, documentation, enhancement

#42 Two hotfixes
  src/Exercise02AI.ipynb
  src/Exercise04AI.ipynb
  src/Main.ipynb
  statistics/statistics.xlsx
  statistics/statistics_gamefiles.zip
Labels: bug
